env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
dockers:
  - image_templates:
    - "push.soh.re/splitshift:{{ .Tag }}"
    - "push.soh.re/splitshift:latest"
    extra_files:
    - error.gtpl
    - upload.gtpl

nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://soh.re
  description: A http server to read a CSV file containing shifts, and split them if they go past midnight
  maintainer: Jonathan Seth Mainguy <jon@soh.re>
  license: GPLv2
  vendor: Jmainguy
  release: 1
  replacements:
    amd64: x86_64
  overrides:
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{.Release}}.{{ .Arch }}"
  formats:
  - rpm

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
